In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.decomposition import FastICA
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.ensemble import IsolationForest
from sklearn.cluster import DBSCAN
import umap
import hdbscan

C:\Users\Lukasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


### Wczytanie danych

In [2]:
hc_training = pd.read_csv('../../../classifier_data/HC_training.csv', sep='\t').T
hc_test = pd.read_csv('../../../classifier_data/HC_test.csv', sep='\t').T
oc_training = pd.read_csv('../../../classifier_data/OC_training.csv', sep='\t').T
oc_test = pd.read_csv('../../../classifier_data/OC_test.csv', sep='\t').T

synthetic_hc_data_path = '../../../best_models/HC/GAN/500/synthetic_data/'
model_id = os.listdir(synthetic_hc_data_path)[0]
hc_synthetic = pd.read_csv(f'{synthetic_hc_data_path}/{model_id}/generated_data.tsv', sep='\t')

synthetic_oc_data_path = '../../../best_models/OC/GAN/500/synthetic_data/'
model_id = os.listdir(synthetic_oc_data_path)[0]
oc_synthetic = pd.read_csv(f'{synthetic_oc_data_path}/{model_id}/generated_data.tsv', sep='\t')

# combine training and test data with labels
hc_training['label'] = 'HC'
hc_test['label'] = 'HC'
oc_training['label'] = 'OC'
oc_test['label'] = 'OC'

hc_synthetic['label'] = 'HC'
oc_synthetic['label'] = 'OC'

training_data = pd.concat([hc_training, oc_training])
test_data = pd.concat([hc_test, oc_test])

In [3]:
# keep only the columns that are in both datasets
# Znalezienie wspólnych kolumn
common_columns = training_data.columns.intersection(test_data.columns)
common_columns = common_columns.intersection(hc_synthetic.columns)
common_columns = common_columns.intersection(oc_synthetic.columns)

# Uporządkowanie kolumn w real_data
training_data = training_data[common_columns]

# Uporządkowanie kolumn w synthetic_data
test_data = test_data[common_columns]

# Uporządkowanie kolumn w synthetic_data
hc_synthetic = hc_synthetic[common_columns]
oc_synthetic = oc_synthetic[common_columns]

common_columns

Index(['ENSG00000000938', 'ENSG00000005844', 'ENSG00000009790',
       'ENSG00000010327', 'ENSG00000011422', 'ENSG00000011600',
       'ENSG00000012779', 'ENSG00000013364', 'ENSG00000013441',
       'ENSG00000018280',
       ...
       'ENSG00000229164', 'ENSG00000231500', 'ENSG00000240356',
       'ENSG00000244038', 'ENSG00000244734', 'ENSG00000257207',
       'ENSG00000266714', 'ENSG00000269028', 'ENSG00000271043', 'label'],
      dtype='object', length=356)

In [4]:
# add synthetic data to training data
training_data_synthetic = pd.concat([training_data, hc_synthetic, oc_synthetic])
training_data_synthetic

ENSG00000000938  ENSG00000005844  \
VUMC-HC-0033-TR2591                   4.432779         4.211676   
Vumc-HD-70-TR1062                     5.786592         5.247890   
VUMC-HC0053-DOT-HD-48h-TR3087         5.526849         4.934939   
Vumc-HD-149-TR932                     4.923042         3.937986   
Vumc-HD-36-TR1165                     6.484772         5.938859   
...                                        ...              ...   
76                                    5.082312         3.911660   
77                                    7.436170         4.655952   
78                                    5.483462         4.751183   
79                                    4.885800         4.299527   
80                                    4.717401         3.600277   

                               ENSG00000009790  ENSG00000010327  \
VUMC-HC-0033-TR2591                   4.252125         4.399111   
Vumc-HD-70-TR1062                     5.983595         3.522177   
VUMC-HC0053-DOT-HD-48h-TR3087         5.442502         4.588670   
Vumc-HD-149-TR932                     4.556107         3.083092   
Vumc-HD-36-TR1165                     7.417415         5.998264   
...                                        ...              ...   
76                                    4.391954         4.422076   
77                                    5.136782         6.478771   
78                                    5.469004         4.953446   
79                                    4.915200         4.677895   
80                                    4.396552         4.090046   

                               ENSG00000011422  ENSG00000011600  \
VUMC-HC-0033-TR2591                   3.083092         4.586923   
Vumc-HD-70-TR1062                     3.522177         6.188222   
VUMC-HC0053-DOT-HD-48h-TR3087         3.535847         4.956248   
Vumc-HD-149-TR932                     3.083092         5.010208   
Vumc-HD-36-TR1165                     3.083092         5.998264   
...                                        ...              ...   
76                                    3.480028         4.802453   
77                                    4.086277         5.525692   
78                                    4.479723         5.890906   
79                                    3.853819         5.665267   
80                                    3.454970         4.773148   

                               ENSG00000012779  ENSG00000013364  \
VUMC-HC-0033-TR2591                   4.211676         4.820505   
Vumc-HD-70-TR1062                     5.368589         4.842162   
VUMC-HC0053-DOT-HD-48h-TR3087         4.559495         5.442502   
Vumc-HD-149-TR932                     4.234439         4.988981   
Vumc-HD-36-TR1165                     5.339481         6.262440   
...                                        ...              ...   
76                                    4.033826         4.469498   
77                                    5.010839         5.486755   
78                                    4.925531         5.970249   
79                                    4.171181         5.181170   
80                                    3.637081         4.599307   

                               ENSG00000013441  ENSG00000018280  ...  \
VUMC-HC-0033-TR2591                   4.328301         4.029213  ...   
Vumc-HD-70-TR1062                     5.114879         3.837909  ...   
VUMC-HC0053-DOT-HD-48h-TR3087         4.467036         4.079708  ...   
Vumc-HD-149-TR932                     4.275620         3.083092  ...   
Vumc-HD-36-TR1165                     6.564767         5.241598  ...   
...                                        ...              ...  ...   
76                                    4.577241         4.319013  ...   
77                                    4.507426         4.958651  ...   
78                                    5.951266         4.878417  ...   
79                                    5.255667         4.246846  ...   
80                 

### Wykorzystanie klasyfikatorów

In [5]:
# klasyfikacja z uyciem svm
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score


def svm_classification(training_data, test_data):
    # Oddziel etykiety od cech
    X_train = training_data.drop('label', axis=1)
    y_train = training_data['label']
    X_test = test_data.drop('label', axis=1)
    y_test = test_data['label']

    # Normalizacja danych
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    # Klasyfikacja przy użyciu SVM
    svm = SVC(kernel='linear', random_state=42)
    svm.fit(X_train, y_train)
    y_pred = svm.predict(X_test)

    # Wypisanie dokładności i innych metryk
    print(f"Dokładność: {accuracy_score(y_test, y_pred)}")
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))


svm_classification(training_data, test_data)
svm_classification(training_data_synthetic, test_data)

Dokładność: 0.9081081081081082
              precision    recall  f1-score   support

          HC       0.94      0.93      0.93       131
          OC       0.84      0.85      0.84        54

    accuracy                           0.91       185
   macro avg       0.89      0.89      0.89       185
weighted avg       0.91      0.91      0.91       185

[[122   9]
 [  8  46]]
Dokładność: 0.8972972972972973
              precision    recall  f1-score   support

          HC       0.93      0.92      0.93       131
          OC       0.82      0.83      0.83        54

    accuracy                           0.90       185
   macro avg       0.87      0.88      0.88       185
weighted avg       0.90      0.90      0.90       185

[[121  10]
 [  9  45]]


In [6]:
from sklearn.tree import DecisionTreeClassifier
# klasyfikacja z uyciem random forest
def decision_tree_classification(training_data, test_data):
    # Oddziel etykiety od cech
    X_train = training_data.drop('label', axis=1)
    y_train = training_data['label']
    X_test = test_data.drop('label', axis=1)
    y_test = test_data['label']

    # Normalizacja danych
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)
    
    # Klasyfikacja
    dt = DecisionTreeClassifier(max_depth=5, random_state=42)
    dt.fit(X_train, y_train)
    y_pred = dt.predict(X_test)

    # Wypisanie dokładności i innych metryk
    print(f"Dokładność: {accuracy_score(y_test, y_pred)}")
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))

decision_tree_classification(training_data, test_data)
decision_tree_classification(training_data_synthetic, test_data)

Dokładność: 0.7945945945945946
              precision    recall  f1-score   support

          HC       0.83      0.89      0.86       131
          OC       0.67      0.57      0.62        54

    accuracy                           0.79       185
   macro avg       0.75      0.73      0.74       185
weighted avg       0.79      0.79      0.79       185

[[116  15]
 [ 23  31]]
Dokładność: 0.8108108108108109
              precision    recall  f1-score   support

          HC       0.87      0.86      0.87       131
          OC       0.67      0.69      0.68        54

    accuracy                           0.81       185
   macro avg       0.77      0.77      0.77       185
weighted avg       0.81      0.81      0.81       185

[[113  18]
 [ 17  37]]


In [7]:
from sklearn.ensemble import RandomForestClassifier
# klasyfikacja z uyciem random forest
def random_forest_classification(training_data, test_data):
    # Oddziel etykiety od cech
    X_train = training_data.drop('label', axis=1)
    y_train = training_data['label']
    X_test = test_data.drop('label', axis=1)
    y_test = test_data['label']

    # Normalizacja danych
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)
    
    # Klasyfikacja
    rf = RandomForestClassifier(n_estimators=100, random_state=42)
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)

    # Wypisanie dokładności i innych metryk
    print(f"Dokładność: {accuracy_score(y_test, y_pred)}")
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))

random_forest_classification(training_data, test_data)
random_forest_classification(training_data_synthetic, test_data)

Dokładność: 0.8486486486486486
              precision    recall  f1-score   support

          HC       0.83      0.98      0.90       131
          OC       0.93      0.52      0.67        54

    accuracy                           0.85       185
   macro avg       0.88      0.75      0.78       185
weighted avg       0.86      0.85      0.83       185

[[129   2]
 [ 26  28]]
Dokładność: 0.8648648648648649
              precision    recall  f1-score   support

          HC       0.85      0.98      0.91       131
          OC       0.94      0.57      0.71        54

    accuracy                           0.86       185
   macro avg       0.89      0.78      0.81       185
weighted avg       0.88      0.86      0.85       185

[[129   2]
 [ 23  31]]


In [8]:
from xgboost import XGBClassifier

# klasyfikacja z uyciem xgboost
def xgboost_classification(training_data, test_data):
    # Oddziel etykiety od cech
    X_train = training_data.drop('label', axis=1)
    y_train = training_data['label']
    X_test = test_data.drop('label', axis=1)
    y_test = test_data['label']

    # Normalizacja danych
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)
    
    # Klasyfikacja
    y_train = y_train.replace('HC', 0)
    y_train = y_train.replace('OC', 1)
    y_test = y_test.replace('HC', 0)
    y_test = y_test.replace('OC', 1)
    xgb = XGBClassifier(random_state=42)
    xgb.fit(X_train, y_train)
    y_pred = xgb.predict(X_test)

    # Wypisanie dokładności i innych metryk
    print(f"Dokładność: {accuracy_score(y_test, y_pred)}")
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))

xgboost_classification(training_data, test_data)
xgboost_classification(training_data_synthetic, test_data)

Dokładność: 0.8810810810810811
              precision    recall  f1-score   support

           0       0.89      0.95      0.92       131
           1       0.85      0.72      0.78        54

    accuracy                           0.88       185
   macro avg       0.87      0.83      0.85       185
weighted avg       0.88      0.88      0.88       185

[[124   7]
 [ 15  39]]
Dokładność: 0.8756756756756757
              precision    recall  f1-score   support

           0       0.88      0.96      0.92       131
           1       0.88      0.67      0.76        54

    accuracy                           0.88       185
   macro avg       0.88      0.81      0.84       185
weighted avg       0.88      0.88      0.87       185

[[126   5]
 [ 18  36]]


In [9]:
from sklearn.neural_network import MLPClassifier

# klasyfikacja z uzyciem sieci neuronowych

def nn_classification(training_data, test_data):
    # Oddziel etykiety od cech
    X_train = training_data.drop('label', axis=1)
    y_train = training_data['label']
    X_test = test_data.drop('label', axis=1)
    y_test = test_data['label']

    # Normalizacja danych
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)
    
    # Klasyfikacja
    nn = MLPClassifier(hidden_layer_sizes=(100,100), random_state=42)
    nn.fit(X_train, y_train)
    y_pred = nn.predict(X_test)

    # Wypisanie dokładności i innych metryk
    print(f"Dokładność: {accuracy_score(y_test, y_pred)}")
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))

nn_classification(training_data, test_data)
nn_classification(training_data_synthetic, test_data)

Dokładność: 0.918918918918919
              precision    recall  f1-score   support

          HC       0.93      0.96      0.94       131
          OC       0.90      0.81      0.85        54

    accuracy                           0.92       185
   macro avg       0.91      0.89      0.90       185
weighted avg       0.92      0.92      0.92       185

[[126   5]
 [ 10  44]]
Dokładność: 0.8972972972972973
              precision    recall  f1-score   support

          HC       0.91      0.95      0.93       131
          OC       0.87      0.76      0.81        54

    accuracy                           0.90       185
   macro avg       0.89      0.86      0.87       185
weighted avg       0.90      0.90      0.90       185

[[125   6]
 [ 13  41]]
